// GENERATED by scripts/seed.py - do not edit by hand.
// Rerun the seed to change what is listed here.

import c_houston from "./houston.json";
import c_phoenix from "./phoenix.json";
import c_lasvegas from "./lasvegas.json";
import c_austin from "./austin.json";
import c_miami from "./miami.json";

/** Every surveyed metro, largest urban footprint first. */
export const CITY_ORDER: string[] = [
  "houston",
  "phoenix",
  "lasvegas",
  "austin",
  "miami",
];

export const CITY_JSON: Record<string, unknown> = {
  "houston": c_houston,
  "phoenix": c_phoenix,
  "lasvegas": c_lasvegas,
  "austin": c_austin,
  "miami": c_miami,
};
