// GENERATED by scripts/seed.py - do not edit by hand.
// Rerun the seed to change what is listed here.

import c_newyork from "./newyork.json";
import c_atlanta from "./atlanta.json";
import c_chicago from "./chicago.json";
import c_philadelphia from "./philadelphia.json";
import c_houston from "./houston.json";
import c_dallas from "./dallas.json";
import c_boston from "./boston.json";
import c_losangeles from "./losangeles.json";
import c_washington from "./washington.json";
import c_detroit from "./detroit.json";
import c_phoenix from "./phoenix.json";
import c_seattle from "./seattle.json";
import c_tampa from "./tampa.json";
import c_stlouis from "./stlouis.json";
import c_pittsburgh from "./pittsburgh.json";
import c_cincinnati from "./cincinnati.json";
import c_indianapolis from "./indianapolis.json";
import c_cleveland from "./cleveland.json";
import c_sandiego from "./sandiego.json";
import c_charlotte from "./charlotte.json";
import c_baltimore from "./baltimore.json";
import c_orlando from "./orlando.json";
import c_denver from "./denver.json";
import c_sanantonio from "./sanantonio.json";
import c_riverside from "./riverside.json";
import c_nashville_davidson from "./nashville-davidson.json";
import c_jacksonville from "./jacksonville.json";
import c_raleigh from "./raleigh.json";
import c_providence from "./providence.json";
import c_hartford from "./hartford.json";
import c_portland from "./portland.json";
import c_columbus from "./columbus.json";
import c_sanfrancisco from "./sanfrancisco.json";
import c_richmond from "./richmond.json";
import c_birmingham from "./birmingham.json";
import c_memphis from "./memphis.json";
import c_virginiabeach from "./virginiabeach.json";
import c_sacramento from "./sacramento.json";
import c_milwaukee from "./milwaukee.json";
import c_lasvegas from "./lasvegas.json";
import c_knoxville from "./knoxville.json";
import c_oklahomacity from "./oklahomacity.json";
import c_louisvillejeffersoncounty from "./louisvillejeffersoncounty.json";
import c_bridgeport from "./bridgeport.json";
import c_columbia from "./columbia.json";
import c_tucson from "./tucson.json";
import c_buffalo from "./buffalo.json";
import c_charleston from "./charleston.json";
import c_tulsa from "./tulsa.json";
import c_capecoral from "./capecoral.json";
import c_mcallen from "./mcallen.json";
import c_dayton from "./dayton.json";
import c_winston_salem from "./winston-salem.json";
import c_akron from "./akron.json";
import c_saltlakecity from "./saltlakecity.json";
import c_newhaven from "./newhaven.json";
import c_rochester from "./rochester.json";
import c_chattanooga from "./chattanooga.json";
import c_sanjose from "./sanjose.json";
import c_grandrapids from "./grandrapids.json";
import c_augusta_richmondcounty from "./augusta-richmondcounty.json";
import c_albany from "./albany.json";
import c_omaha from "./omaha.json";
import c_neworleans from "./neworleans.json";
import c_littlerock from "./littlerock.json";
import c_albuquerque from "./albuquerque.json";
import c_pensacola from "./pensacola.json";
import c_greenville from "./greenville.json";
import c_allentown from "./allentown.json";
import c_elpaso from "./elpaso.json";
import c_palmbay from "./palmbay.json";
import c_harrisburg from "./harrisburg.json";
import c_asheville from "./asheville.json";
import c_toledo from "./toledo.json";
import c_jackson from "./jackson.json";
import c_wichita from "./wichita.json";
import c_desmoines from "./desmoines.json";
import c_mobile from "./mobile.json";
import c_myrtlebeach from "./myrtlebeach.json";
import c_huntsville from "./huntsville.json";
import c_ogden from "./ogden.json";
import c_savannah from "./savannah.json";
import c_flint from "./flint.json";
import c_springfield from "./springfield.json";
import c_coloradosprings from "./coloradosprings.json";
import c_fayetteville from "./fayetteville.json";
import c_youngstown from "./youngstown.json";
import c_nashua from "./nashua.json";
import c_shreveport from "./shreveport.json";
import c_syracuse from "./syracuse.json";
import c_spokane from "./spokane.json";
import c_greensboro from "./greensboro.json";
import c_gulfport from "./gulfport.json";
import c_reno from "./reno.json";
import c_missionviejo from "./missionviejo.json";
import c_fortwayne from "./fortwayne.json";
import c_atlanticcity from "./atlanticcity.json";
import c_scranton from "./scranton.json";
import c_lafayette from "./lafayette.json";
import c_fresno from "./fresno.json";
import c_lansing from "./lansing.json";
import c_indio from "./indio.json";
import c_madison from "./madison.json";
import c_southbend from "./southbend.json";
import c_bremerton from "./bremerton.json";
import c_peoria from "./peoria.json";
import c_montgomery from "./montgomery.json";
import c_annarbor from "./annarbor.json";
import c_columbus_19099 from "./columbus-19099.json";
import c_boisecity from "./boisecity.json";
import c_davenport from "./davenport.json";
import c_springfield_83953 from "./springfield-83953.json";
import c_rockford from "./rockford.json";
import c_trenton from "./trenton.json";
import c_bakersfield from "./bakersfield.json";
import c_corpuschristi from "./corpuschristi.json";
import c_huntington from "./huntington.json";
import c_phoenixwest from "./phoenixwest.json";
import c_roanoke from "./roanoke.json";
import c_tallahassee from "./tallahassee.json";
import c_portland_71263 from "./portland-71263.json";
import c_navarre from "./navarre.json";
import c_norwich from "./norwich.json";
import c_greenbay from "./greenbay.json";
import c_clarksville from "./clarksville.json";
import c_evansville from "./evansville.json";
import c_kennewick from "./kennewick.json";
import c_muskegon from "./muskegon.json";
import c_galveston from "./galveston.json";
import c_deltona from "./deltona.json";
import c_lubbock from "./lubbock.json";
import c_olympia from "./olympia.json";
import c_mauldin from "./mauldin.json";
import c_killeen from "./killeen.json";
import c_macon_bibbcounty from "./macon-bibbcounty.json";
import c_beaumont from "./beaumont.json";
import c_reading from "./reading.json";
import c_lincoln from "./lincoln.json";
import c_charleston_15481 from "./charleston-15481.json";
import c_stockton from "./stockton.json";
import c_athens_clarkecounty from "./athens-clarkecounty.json";
import c_lynchburg from "./lynchburg.json";
import c_monroe from "./monroe.json";
import c_miami from "./miami.json";
import c_austin from "./austin.json";
import c_bonitasprings from "./bonitasprings.json";
import c_canton from "./canton.json";
import c_concord from "./concord.json";
import c_kissimmee from "./kissimmee.json";
import c_kalamazoo from "./kalamazoo.json";
import c_elkhart from "./elkhart.json";
import c_longview from "./longview.json";
import c_waco from "./waco.json";
import c_fredericksburg from "./fredericksburg.json";
import c_warnerrobins from "./warnerrobins.json";
import c_tuscaloosa from "./tuscaloosa.json";
import c_cedarrapids from "./cedarrapids.json";
import c_odessa from "./odessa.json";
import c_palmdale from "./palmdale.json";
import c_topeka from "./topeka.json";
import c_lexington_fayette from "./lexington-fayette.json";
import c_amarillo from "./amarillo.json";
import c_tyler from "./tyler.json";
import c_manchester from "./manchester.json";
import c_thousandoaks from "./thousandoaks.json";
import c_santarosa from "./santarosa.json";
import c_anniston from "./anniston.json";
import c_santaclarita from "./santaclarita.json";
import c_fargo from "./fargo.json";
import c_oxnard from "./oxnard.json";

/** Every surveyed metro, largest urban footprint first. */
export const CITY_ORDER: string[] = [
  "newyork",
  "atlanta",
  "chicago",
  "philadelphia",
  "houston",
  "dallas",
  "boston",
  "losangeles",
  "washington",
  "detroit",
  "phoenix",
  "seattle",
  "tampa",
  "stlouis",
  "pittsburgh",
  "cincinnati",
  "indianapolis",
  "cleveland",
  "sandiego",
  "charlotte",
  "baltimore",
  "orlando",
  "denver",
  "sanantonio",
  "riverside",
  "nashville-davidson",
  "jacksonville",
  "raleigh",
  "providence",
  "hartford",
  "portland",
  "columbus",
  "sanfrancisco",
  "richmond",
  "birmingham",
  "memphis",
  "virginiabeach",
  "sacramento",
  "milwaukee",
  "lasvegas",
  "knoxville",
  "oklahomacity",
  "louisvillejeffersoncounty",
  "bridgeport",
  "columbia",
  "tucson",
  "buffalo",
  "charleston",
  "tulsa",
  "capecoral",
  "mcallen",
  "dayton",
  "winston-salem",
  "akron",
  "saltlakecity",
  "newhaven",
  "rochester",
  "chattanooga",
  "sanjose",
  "grandrapids",
  "augusta-richmondcounty",
  "albany",
  "omaha",
  "neworleans",
  "littlerock",
  "albuquerque",
  "pensacola",
  "greenville",
  "allentown",
  "elpaso",
  "palmbay",
  "harrisburg",
  "asheville",
  "toledo",
  "jackson",
  "wichita",
  "desmoines",
  "mobile",
  "myrtlebeach",
  "huntsville",
  "ogden",
  "savannah",
  "flint",
  "springfield",
  "coloradosprings",
  "fayetteville",
  "youngstown",
  "nashua",
  "shreveport",
  "syracuse",
  "spokane",
  "greensboro",
  "gulfport",
  "reno",
  "missionviejo",
  "fortwayne",
  "atlanticcity",
  "scranton",
  "lafayette",
  "fresno",
  "lansing",
  "indio",
  "madison",
  "southbend",
  "bremerton",
  "peoria",
  "montgomery",
  "annarbor",
  "columbus-19099",
  "boisecity",
  "davenport",
  "springfield-83953",
  "rockford",
  "trenton",
  "bakersfield",
  "corpuschristi",
  "huntington",
  "phoenixwest",
  "roanoke",
  "tallahassee",
  "portland-71263",
  "navarre",
  "norwich",
  "greenbay",
  "clarksville",
  "evansville",
  "kennewick",
  "muskegon",
  "galveston",
  "deltona",
  "lubbock",
  "olympia",
  "mauldin",
  "killeen",
  "macon-bibbcounty",
  "beaumont",
  "reading",
  "lincoln",
  "charleston-15481",
  "stockton",
  "athens-clarkecounty",
  "lynchburg",
  "monroe",
  "miami",
  "austin",
  "bonitasprings",
  "canton",
  "concord",
  "kissimmee",
  "kalamazoo",
  "elkhart",
  "longview",
  "waco",
  "fredericksburg",
  "warnerrobins",
  "tuscaloosa",
  "cedarrapids",
  "odessa",
  "palmdale",
  "topeka",
  "lexington-fayette",
  "amarillo",
  "tyler",
  "manchester",
  "thousandoaks",
  "santarosa",
  "anniston",
  "santaclarita",
  "fargo",
  "oxnard",
];

export const CITY_JSON: Record<string, unknown> = {
  "newyork": c_newyork,
  "atlanta": c_atlanta,
  "chicago": c_chicago,
  "philadelphia": c_philadelphia,
  "houston": c_houston,
  "dallas": c_dallas,
  "boston": c_boston,
  "losangeles": c_losangeles,
  "washington": c_washington,
  "detroit": c_detroit,
  "phoenix": c_phoenix,
  "seattle": c_seattle,
  "tampa": c_tampa,
  "stlouis": c_stlouis,
  "pittsburgh": c_pittsburgh,
  "cincinnati": c_cincinnati,
  "indianapolis": c_indianapolis,
  "cleveland": c_cleveland,
  "sandiego": c_sandiego,
  "charlotte": c_charlotte,
  "baltimore": c_baltimore,
  "orlando": c_orlando,
  "denver": c_denver,
  "sanantonio": c_sanantonio,
  "riverside": c_riverside,
  "nashville-davidson": c_nashville_davidson,
  "jacksonville": c_jacksonville,
  "raleigh": c_raleigh,
  "providence": c_providence,
  "hartford": c_hartford,
  "portland": c_portland,
  "columbus": c_columbus,
  "sanfrancisco": c_sanfrancisco,
  "richmond": c_richmond,
  "birmingham": c_birmingham,
  "memphis": c_memphis,
  "virginiabeach": c_virginiabeach,
  "sacramento": c_sacramento,
  "milwaukee": c_milwaukee,
  "lasvegas": c_lasvegas,
  "knoxville": c_knoxville,
  "oklahomacity": c_oklahomacity,
  "louisvillejeffersoncounty": c_louisvillejeffersoncounty,
  "bridgeport": c_bridgeport,
  "columbia": c_columbia,
  "tucson": c_tucson,
  "buffalo": c_buffalo,
  "charleston": c_charleston,
  "tulsa": c_tulsa,
  "capecoral": c_capecoral,
  "mcallen": c_mcallen,
  "dayton": c_dayton,
  "winston-salem": c_winston_salem,
  "akron": c_akron,
  "saltlakecity": c_saltlakecity,
  "newhaven": c_newhaven,
  "rochester": c_rochester,
  "chattanooga": c_chattanooga,
  "sanjose": c_sanjose,
  "grandrapids": c_grandrapids,
  "augusta-richmondcounty": c_augusta_richmondcounty,
  "albany": c_albany,
  "omaha": c_omaha,
  "neworleans": c_neworleans,
  "littlerock": c_littlerock,
  "albuquerque": c_albuquerque,
  "pensacola": c_pensacola,
  "greenville": c_greenville,
  "allentown": c_allentown,
  "elpaso": c_elpaso,
  "palmbay": c_palmbay,
  "harrisburg": c_harrisburg,
  "asheville": c_asheville,
  "toledo": c_toledo,
  "jackson": c_jackson,
  "wichita": c_wichita,
  "desmoines": c_desmoines,
  "mobile": c_mobile,
  "myrtlebeach": c_myrtlebeach,
  "huntsville": c_huntsville,
  "ogden": c_ogden,
  "savannah": c_savannah,
  "flint": c_flint,
  "springfield": c_springfield,
  "coloradosprings": c_coloradosprings,
  "fayetteville": c_fayetteville,
  "youngstown": c_youngstown,
  "nashua": c_nashua,
  "shreveport": c_shreveport,
  "syracuse": c_syracuse,
  "spokane": c_spokane,
  "greensboro": c_greensboro,
  "gulfport": c_gulfport,
  "reno": c_reno,
  "missionviejo": c_missionviejo,
  "fortwayne": c_fortwayne,
  "atlanticcity": c_atlanticcity,
  "scranton": c_scranton,
  "lafayette": c_lafayette,
  "fresno": c_fresno,
  "lansing": c_lansing,
  "indio": c_indio,
  "madison": c_madison,
  "southbend": c_southbend,
  "bremerton": c_bremerton,
  "peoria": c_peoria,
  "montgomery": c_montgomery,
  "annarbor": c_annarbor,
  "columbus-19099": c_columbus_19099,
  "boisecity": c_boisecity,
  "davenport": c_davenport,
  "springfield-83953": c_springfield_83953,
  "rockford": c_rockford,
  "trenton": c_trenton,
  "bakersfield": c_bakersfield,
  "corpuschristi": c_corpuschristi,
  "huntington": c_huntington,
  "phoenixwest": c_phoenixwest,
  "roanoke": c_roanoke,
  "tallahassee": c_tallahassee,
  "portland-71263": c_portland_71263,
  "navarre": c_navarre,
  "norwich": c_norwich,
  "greenbay": c_greenbay,
  "clarksville": c_clarksville,
  "evansville": c_evansville,
  "kennewick": c_kennewick,
  "muskegon": c_muskegon,
  "galveston": c_galveston,
  "deltona": c_deltona,
  "lubbock": c_lubbock,
  "olympia": c_olympia,
  "mauldin": c_mauldin,
  "killeen": c_killeen,
  "macon-bibbcounty": c_macon_bibbcounty,
  "beaumont": c_beaumont,
  "reading": c_reading,
  "lincoln": c_lincoln,
  "charleston-15481": c_charleston_15481,
  "stockton": c_stockton,
  "athens-clarkecounty": c_athens_clarkecounty,
  "lynchburg": c_lynchburg,
  "monroe": c_monroe,
  "miami": c_miami,
  "austin": c_austin,
  "bonitasprings": c_bonitasprings,
  "canton": c_canton,
  "concord": c_concord,
  "kissimmee": c_kissimmee,
  "kalamazoo": c_kalamazoo,
  "elkhart": c_elkhart,
  "longview": c_longview,
  "waco": c_waco,
  "fredericksburg": c_fredericksburg,
  "warnerrobins": c_warnerrobins,
  "tuscaloosa": c_tuscaloosa,
  "cedarrapids": c_cedarrapids,
  "odessa": c_odessa,
  "palmdale": c_palmdale,
  "topeka": c_topeka,
  "lexington-fayette": c_lexington_fayette,
  "amarillo": c_amarillo,
  "tyler": c_tyler,
  "manchester": c_manchester,
  "thousandoaks": c_thousandoaks,
  "santarosa": c_santarosa,
  "anniston": c_anniston,
  "santaclarita": c_santaclarita,
  "fargo": c_fargo,
  "oxnard": c_oxnard,
};
